### ISSUE TITLE
Blinn-phong shader in numpy

### ISSUE THREAD

**Issue by D-K-E** [dbohdan/unflattener#3]
Hi,
Nice project you have here. I would just like to say that I have implemented a blinn-phong shader in numpy as a part of my [project](https://github.com/D-K-E/ptm-viewer/blob/2babf710693e13c497fd6f99272af7d083d60f4b/main/core.py#L293). 

Feel free to add it to your code base if you think it is worth the effort to add dynamic lightning changes to `unflattener`. It is pretty slow though, since everything runs in cpu. I'll see if I can implement a gpu backend for the same project for real time effects.

**Comment by dbohdan** [comment]
This is pretty neat.  I do not plan on implementing my own lighting preview in unflattener or adding other new features, but I have put the link to your shader on the project [wiki](https://github.com/dbohdan/unflattener/wiki) (which I've long meant to create).  I would suggest rereleasing the shader under a more liberal license if you want others to use it.
